import type { NextPage } from "next";
import Head from "next/head";
import QuoteGen from "../components/QuoteGen/QuoteGen";

const Home: NextPage = () => {
  return (
    <div className="mx-auto container flex justify-between align-center max-w-4xl">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className=" flex justify-center flex-col w-full mt-4">
        <p className="text-5xl text-center">Typing meter</p>
        <QuoteGen />
      </div>
    </div>
  );
};

export default Home;
